---
{{- if .Values.grpc.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-grpcint
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPCS"
    {{- range $key, $value := .Values.grpc.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: nginx-internal
  rules:
  - host: {{ .Values.name }}.grpc.{{ .Values.grpc.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.name }}
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.name }}.grpc.{{ .Values.grpc.host }}
    secretName: wildcard.{{ .Values.grpc.host }}
{{- end }}
