{{ range .Values.Deployment.containers }}
{{- if .SecretProviderClass.azure.create }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .name }}-secrets
  namespace: {{ $.Values.app.namespace }}
spec:
  parameters:
    keyvaultName: {{ .SecretProviderClass.azure.name }}
    objects: |
      array:
      {{- range .SecretProviderClass.azure.secrets }}
      - |
        objectName: {{ .name }}
        objectType: secret
        objectVersion: ""
      {{- end }}
    tenantId: {{ .SecretProviderClass.azure.tenantId }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .SecretProviderClass.azure.userAssignedIdentityID }}
  provider: azure
  secretObjects:
  - data:
    {{- range .SecretProviderClass.azure.secrets }}
    - key: {{ .name }}
      objectName: {{ .name }}
    {{- end }}
    secretName: {{ $.Values.app.name }}-{{ .SecretProviderClass.azure.name }}-{{ .name }}
    type: Opaque
{{ end }}
{{ end }}
