{{- if .Values.alerts.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  groups:
  - name: {{ .Values.name }}
    rules:
    - alert: KubernetesContainerOomKiller-{{ .Values.name }}
      annotations:
        description: "Container {{`{{ $labels.container }}`}} in pod {{`{{ $labels.namespace }}`}}/{{`{{ $labels.pod }}`}} has been OOMKilled {{`{{ $value }}`}} times in the last 10 minutes.\n  VALUE = {{`{{ $value }}`}}\n  LABELS = {{`{{ $labels }}`}}"
        summary: "Kubernetes container oom killer (Namespace: {{`{{ $labels.namespace }}`}} Pod: {{`{{ $labels.pod }}`}})"
      expr: (kube_pod_container_status_restarts_total{container="{{ .Values.name }}"} - kube_pod_container_status_restarts_total{container="{{ .Values.name }}"}  offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled",container="{{ .Values.name }}"}[10m]) == 1
      for: 0s
      labels:
        severity: critical
    - alert: KubernetesPodNotHealthy-{{ .Values.name }}
      annotations:
        description: "Pod has been in a non-ready state for longer than 15 minutes.\n  VALUE = {{`{{ $value }}`}}\n  LABELS = {{`{{ $labels }}`}}"
        summary: "Kubernetes Pod not healthy (Namespace: {{`{{ $labels.namespace }}`}} Pod: {{`{{ $labels.pod }}`}} Status: {{`{{ $labels.phase }}`}})"
      expr: min_over_time(sum by (namespace, pod, phase) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed",container="{{ .Values.name }}"})[15m:1m]) > 0
      for: 0s
      labels:
        severity: critical
    - alert: KubernetesPodCrashLooping-{{ .Values.name }}
      annotations:
        description: "Pod {{`{{ $labels.pod }}`}} is crash looping\n  VALUE ={{` {{ $value }}`}}\n  LABELS = {{`{{ $labels }}`}}"
        summary: "Kubernetes pod crash looping (Namespace: {{`{{ $labels.namespace }}`}} Pod: {{`{{ $labels.pod }}`}})"
      expr: increase(kube_pod_container_status_restarts_total{container="{{ .Values.name }}"}[1m]) > 3
      for: 2m
      labels:
        severity: critical
{{- if .Values.healthProbe.enabled }}
    - alert: BlackboxProbeHttpFailure-{{ .Values.name }}
      annotations:
        description: |-
          HTTP status code is not 200-399
            VALUE = {{`{{ $value }}`}}
            LABELS = {{`{{ $labels }}`}}
        summary: HTTP probe for {{`{{ $labels.instance }}`}}
      expr: probe_http_status_code{target="{{ .Values.name }}-{{ .Values.namespace }}"} <= 199 OR probe_http_status_code{target="{{ .Values.name }}-{{ .Values.namespace }}"} >= 400
      for: 0s
      labels:
        severity: critical
{{- end }}
{{- end }}
