{{ range .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-fetcher
  namespace: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: vault-fetcher
spec:
  selector:
    matchLabels:
      app: vault-fetcher
  replicas: 1
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
      labels:
        app: vault-fetcher
    spec:
      imagePullSecrets:
        {{ $.Values.imagePullSecrets | toYaml | nindent 8 }}
      nodeSelector:
        {{ $.Values.nodeSelector | toYaml | nindent 8 }}
      serviceAccountName: vault-fetcher
      containers:
      - image: {{ $.Values.image }}
        imagePullPolicy: IfNotPresent
        name: vault-fetcher
        volumeMounts:
        - name: secrets-mount
          mountPath: "/mnt/dummy"
          readOnly: true
      volumes:
        - name: secrets-mount
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: vault-fetcher
{{- end }}
