{{ range .Values.services }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-fetcher
  namespace: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider: vault
  secretObjects:
  - secretName: netigate
    data:
    - key: .dockerconfigjson
      objectName: imagePullSecretNetigate
    type: kubernetes.io/dockerconfigjson
  {{- range $.Values.internalIngressCertificates }}
  - secretName: {{ .kubernetesSecretName }}
    data:
      - key: tls.crt
        objectName: chain-{{ .certificateName }}
      - key: tls.key
        objectName: key-{{ .certificateName }}
    type: kubernetes.io/tls
  {{- end }}
  {{- range .certificates }}
  - secretName: {{ . }}
    data:
    - key: tls.crt
      objectName: chain-{{ . }}
    - key: tls.key
      objectName: key-{{ . }}
    type: kubernetes.io/tls
  {{- end }}
  parameters:
    vaultAddress: {{ $.Values.vaultAddress }}
    roleName: vault-fetcher
    objects: |
      - objectName: "imagePullSecretNetigate"
        secretPath: "imagepullsecrets/data/netigate"
        secretKey: "dockerconfigjson"
      {{- range $.Values.internalIngressCertificates }}
      - objectName: "chain-{{ .certificateName }}"
        secretPath: "certificates/data/{{ .certificateName }}"
        secretKey: "chain_pem"
      - objectName: "key-{{ .certificateName }}"
        secretPath: "certificates/data/{{ .certificateName }}"
        secretKey: "private_key_pem"
      {{- end }}
      {{- range .certificates }}
      - objectName: "chain-{{ . }}"
        secretPath: "certificates/data/{{ . }}"
        secretKey: "chain_pem"
      - objectName: "key-{{ . }}"
        secretPath: "certificates/data/{{ . }}"
        secretKey: "private_key_pem"
      {{- end }}
{{- end }}
