app:
  name:
  namespace:

Deployment:
  create:
  replicas: 1 # Must be null if horizontalPodAutoscaler is true, TBD
  nodeSelector:
    kubernetes.netigate.net/os: windows
    kubernetes.netigate.net/role: user
    kubernetes.netigate.net/mode: highmemory
  containers:
    - name:
      image:
      resources:
        limits:
          cpu: 0.1
          memory: 80M
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      SecretProviderClass:
        azure:
          create: false
          name:
          tenantId:
          userAssignedIdentityID:
          secrets:
            - name:
              envVarName:

Ingress:
  external:
    create: true
    annotations:
      cert-manager.io/issuer: "letsencrypt-staging"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host:
        path:
        secretName:
