---
apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace-config
  namespace: {{ .Values.onlycerts.namespace }}
data:
  certmap.yaml: |-
    namespaces: {{ range .Values.services }}{{ if .certificates }}
    - name: {{ .name }}
      certificates: {{ range .certificates }}
      - name: {{ . }}
      {{- end -}}
      {{- end }}{{ else }} []
    {{ end -}}
