{{ range .Values.services }}
{{- if .pullSecrets }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagepullsecret-fetcher
  namespace: {{ .name }}
  labels:
    app: imagepullsecret-fetcher
spec:
  selector:
    matchLabels:
      app: imagepullsecret-fetcher
  replicas: 1
  template:
    metadata:
      labels:
        app: imagepullsecret-fetcher
    spec:
      serviceAccountName: imagepullsecret-fetcher
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: imagepullsecret-fetcher
        volumeMounts:
        - name: secrets-mount
          mountPath: "/mnt/dummy"
          readOnly: true
      volumes:
        - name: secrets-mount
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: imagepullsecret-fetcher
---
{{- end }}
{{ end }}