{{- if .Values.certificates }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{.Values._internal_name}}
  namespace: {{ .Values.namespace }}
spec:
  provider: vault
  secretObjects:
  {{- range .Values.imagePullSecrets}}
  - secretName: {{ . }}
    data:
    - key: .dockerconfigjson
      objectName: {{ . }}
    type: kubernetes.io/dockerconfigjson
  {{- end }}
  {{- range .Values.certificates }}
  - secretName: {{ . }}
    data:
    - key: tls.crt
      objectName: chain-{{ . }}
    - key: tls.key
      objectName: key-{{ . }}
    type: kubernetes.io/tls
  {{- end }}
  parameters:
    vaultAddress: {{ $.Values.vaultAddress }}
    roleName: {{.Values._internal_name}}
    objects: |
      {{- range .Values.imagePullSecrets }}
      - objectName: "{{ . }}"
        secretPath: "imagepullsecrets/data/{{ . }}"
        secretKey: "dockerconfigjson"
      {{- end }}
      {{- range .Values.certificates }}
      - objectName: "chain-{{ . }}"
        secretPath: "certificates/data/{{ . }}"
        secretKey: "chain_pem"
      - objectName: "key-{{ . }}"
        secretPath: "certificates/data/{{ . }}"
        secretKey: "private_key_pem"
      {{- end }}
{{- end }}