apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6IHsibmV0aWdhdGUuYXp1cmVjci5pbyI6IHsidXNlcm5hbWUiOiAibmV0aWdhdGUiLCAicGFzc3dvcmQiOiAiaXpYQlNHOTJUTk8rRk83SzkwVkRiYnViN0VjVnIzSmsiLCAiYXV0aCI6ICJibVYwYVdkaGRHVTZhWHBZUWxOSE9USlVUazhyUms4M1N6a3dWa1JpWW5WaU4wVmpWbkl6U21zPSJ9fX0=
kind: Secret
metadata:
  name: netigate
type: kubernetes.io/dockerconfigjson
