apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-web
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-web
    team: {{ .Values.team }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.name }}-web
