---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-vault
  namespace: {{ .Values.namespace }}
spec:
  externalName: {{ .Values.vault.service.vaultFQDN }}
  sessionAffinity: None
  type: ExternalName