{{- if .Values.envVars }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
  namespace:  {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
data:
  {{- range .Values.envVars }}
  {{ .name }}: {{ .data | quote }}
  {{- end }}
{{- end }}
