name: 
namespace:
image:
tag:
team:
environmentFQDN:

existingServiceAccount: false

concurrencyPolicy: Allow
successfulJobsHistoryLimit: 1
failedJobsHistoryLimit: 1
schedule: "5 4 * * *"

imagePullSecrets: []

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 24m
    memory: 128Mi


postgres:
  enabled: false

vault:
  enabled: false

kafka:
  enabled: false

envVars: