{{ range $svc := .Values.services }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    team: {{ $svc.team }}
  annotations:
{{ toYaml  $svc.ingress.annotations | indent 4 }}
  name: {{ $svc.name }}
  namespace: {{ $.Values.namespace }}
spec:
  ingressClassName: {{ $.Values.ingressClass}}
  rules:
    - host: "{{ $svc.ingress.host }}"
      http:
        paths: {{ range $svc.ingress.backend.paths }}
          - backend:
              service:
                name: {{ $svc.name }}
                port:
                  number: {{ $svc.ingress.backend.backendServicePort }}
            path: {{ . }}
            pathType: Prefix
            {{- end }}
  tls:
    - hosts:
        - "{{ .ingress.host }}"
      secretName: {{ .ingress.secretName }}
{{ end }}