apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Values.namespace }}
spec:
  provider: vault
  secretObjects:
  - data:
    {{- range .Values.vault.env }}
    - key: {{ .key }}
      objectName: {{ .key }}
    {{- end }}
    secretName: {{ .Values.name }}-secret
    type: Opaque
  parameters:
    vaultAddress: "{{ .Values.vault.address }}"
    roleName: {{ .Values.name }}
    objects: |
      {{- range .Values.vault.env }}
      - objectName: "{{ .key }}"
        secretPath: "{{ $.Values.vault.team }}/data/{{ $.Values.name }}/config"
        secretKey: "{{ .key }}"
      {{- end }}