apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  endpoints:
    - interval: 15s
      path: /metrics
      port: http-metrics